import { VocabCard } from '../../../../shared/types';

export const CURATED_VOCAB_DECK: VocabCard[] = [
  // Original 12 Cards
  {
    id: 'v1',
    word: 'Eloquent',
    partOfSpeech: 'adjective',
    phonetic: '/ˈɛl.ə.kwənt/',
    difficulty: 'intermediate',
    correctDefinition: 'Fluent or persuasive in speaking or writing; clearly expressing ideas.',
    exampleSentence: 'Her eloquent presentation convinced the executive committee to approve the project.',
    synonyms: ['Articulate', 'Expressive', 'Fluent', 'Persuasive'],
    antonyms: ['Inarticulate', 'Hesitant']
  },
  {
    id: 'v2',
    word: 'Resilient',
    partOfSpeech: 'adjective',
    phonetic: '/rɪˈzɪl.jənt/',
    difficulty: 'beginner',
    correctDefinition: 'Able to withstand or recover quickly from difficult conditions or setbacks.',
    exampleSentence: 'The startup proved resilient despite the sudden market downturn.',
    synonyms: ['Tough', 'Adaptable', 'Robust', 'Enduring'],
    antonyms: ['Fragile', 'Vulnerable']
  },
  {
    id: 'v3',
    word: 'Pragmatic',
    partOfSpeech: 'adjective',
    phonetic: '/præɡˈmæt.ɪk/',
    difficulty: 'intermediate',
    correctDefinition: 'Dealing with things sensibly and realistically in a way that is based on practical rather than theoretical considerations.',
    exampleSentence: 'We need a pragmatic solution that works within our current budget.',
    synonyms: ['Practical', 'Realistic', 'Sensible', 'Hard-headed'],
    antonyms: ['Idealistic', 'Impractical']
  },
  {
    id: 'v4',
    word: 'Ambiguous',
    partOfSpeech: 'adjective',
    phonetic: '/æmˈbɪɡ.ju.əs/',
    difficulty: 'intermediate',
    correctDefinition: 'Open to more than one interpretation; not having one obvious meaning; unclear.',
    exampleSentence: 'The contract contained ambiguous language that led to a legal dispute.',
    synonyms: ['Equivocal', 'Unclear', 'Vague', 'Obscure'],
    antonyms: ['Clear', 'Definite', 'Unambiguous']
  },
  {
    id: 'v5',
    word: 'Ephemeral',
    partOfSpeech: 'adjective',
    phonetic: '/ɪˈfɛm.ər.əl/',
    difficulty: 'advanced',
    correctDefinition: 'Lasting for a very short time; fleeting or transient.',
    exampleSentence: 'Fame on social media can be ephemeral, vanishing as quickly as it arrives.',
    synonyms: ['Transient', 'Fleeting', 'Momentary', 'Short-lived'],
    antonyms: ['Permanent', 'Enduring', 'Eternal']
  },
  {
    id: 'v6',
    word: 'Meticulous',
    partOfSpeech: 'adjective',
    phonetic: '/məˈtɪk.jʊ.ləs/',
    difficulty: 'intermediate',
    correctDefinition: 'Showing great attention to detail; very careful and precise.',
    exampleSentence: 'The architect was meticulous about checking every measurement.',
    synonyms: ['Diligent', 'Scrupulous', 'Painstaking', 'Thorough'],
    antonyms: ['Careless', 'Sloppy', 'Slapdash']
  },
  {
    id: 'v7',
    word: 'Ubiquitous',
    partOfSpeech: 'adjective',
    phonetic: '/juːˈbɪk.wɪ.təs/',
    difficulty: 'advanced',
    correctDefinition: 'Present, appearing, or found everywhere at the same time.',
    exampleSentence: 'Smartphones have become ubiquitous in modern daily life.',
    synonyms: ['Omnipresent', 'Pervasive', 'Prevalent', 'Universal'],
    antonyms: ['Rare', 'Scarce', 'Uncommon']
  },
  {
    id: 'v8',
    word: 'Candor',
    partOfSpeech: 'noun',
    phonetic: '/ˈkæn.dər/',
    difficulty: 'intermediate',
    correctDefinition: 'The quality of being open, honest, and sincere in speech or expression.',
    exampleSentence: 'I appreciate your candor in sharing honest feedback on the draft.',
    synonyms: ['Honesty', 'Frankness', 'Openness', 'Sincerity'],
    antonyms: ['Deceit', 'Dishonesty', 'Insincerity']
  },
  {
    id: 'v9',
    word: 'Benevolent',
    partOfSpeech: 'adjective',
    phonetic: '/bəˈnɛv.əl.ənt/',
    difficulty: 'beginner',
    correctDefinition: 'Well-meaning, kindly, and motivated by a desire to do good to others.',
    exampleSentence: 'A benevolent donor provided scholarships for dozens of underprivileged students.',
    synonyms: ['Kind', 'Generous', 'Altruistic', 'Charitable'],
    antonyms: ['Malevolent', 'Spiteful', 'Hostile']
  },
  {
    id: 'v10',
    word: 'Fastidious',
    partOfSpeech: 'adjective',
    phonetic: '/fæˈstɪd.i.əs/',
    difficulty: 'advanced',
    correctDefinition: 'Very attentive to and concerned about accuracy and detail; hard to please.',
    exampleSentence: 'He was fastidious about the hygiene and preparation in his kitchen.',
    synonyms: ['Demanding', 'Exacting', 'Finicky', 'Punctilious'],
    antonyms: ['Careless', 'Easy-going']
  },
  {
    id: 'v11',
    word: 'Perseverance',
    partOfSpeech: 'noun',
    phonetic: '/ˌpɜː.sɪˈvɪə.rəns/',
    difficulty: 'beginner',
    correctDefinition: 'Persistence in doing something despite difficulty or delay in achieving success.',
    exampleSentence: 'Through perseverance and hard work, she mastered fluent conversational English.',
    synonyms: ['Persistence', 'Tenacity', 'Determination', 'Endurance'],
    antonyms: ['Giving up', 'Hesitation']
  },
  {
    id: 'v12',
    word: 'Serendipity',
    partOfSpeech: 'noun',
    phonetic: '/ˌsɛr.ənˈdɪp.ɪ.ti/',
    difficulty: 'advanced',
    correctDefinition: 'The occurrence and development of events by chance in a happy or beneficial way.',
    exampleSentence: 'Finding my future business partner at an airport was pure serendipity.',
    synonyms: ['Good fortune', 'Chance', 'Fluke', 'Happy accident'],
    antonyms: ['Misfortune', 'Bad luck']
  },

  // 50 NEW CARDS (v13 to v62)
  {
    id: 'v13',
    word: 'Lucid',
    partOfSpeech: 'adjective',
    phonetic: '/ˈluː.sɪd/',
    difficulty: 'intermediate',
    correctDefinition: 'Expressed clearly; easy to understand, or thinking clearly and rationally.',
    exampleSentence: 'The professor gave a lucid explanation of quantum physics.',
    synonyms: ['Clear', 'Intelligible', 'Coherent', 'Luminous'],
    antonyms: ['Confused', 'Murky', 'Obscure']
  },
  {
    id: 'v14',
    word: 'Tenacious',
    partOfSpeech: 'adjective',
    phonetic: '/təˈneɪ.ʃəs/',
    difficulty: 'intermediate',
    correctDefinition: 'Tending to keep a firm hold of something; persistent, resolute, or determined.',
    exampleSentence: 'Her tenacious pursuit of the truth earned her investigative journalism awards.',
    synonyms: ['Persistent', 'Resolute', 'Dogged', 'Determined'],
    antonyms: ['Irresolute', 'Weak', 'Yielding']
  },
  {
    id: 'v15',
    word: 'Empathetic',
    partOfSpeech: 'adjective',
    phonetic: '/ˌɛm.pəˈθɛt.ɪk/',
    difficulty: 'beginner',
    correctDefinition: 'Showing the ability to understand and share the feelings of another.',
    exampleSentence: 'An empathetic leader listens actively to team concerns before making decisions.',
    synonyms: ['Compassionate', 'Understanding', 'Sympathetic', 'Caring'],
    antonyms: ['Callous', 'Indifferent', 'Unfeeling']
  },
  {
    id: 'v16',
    word: 'Innovative',
    partOfSpeech: 'adjective',
    phonetic: '/ˈɪn.ə.veɪ.tɪv/',
    difficulty: 'beginner',
    correctDefinition: 'Featuring new methods; advanced and original in design or concept.',
    exampleSentence: 'The engineering team developed an innovative water filtration device.',
    synonyms: ['Original', 'Inventive', 'Pioneering', 'Novel'],
    antonyms: ['Traditional', 'Derivative', 'Stale']
  },
  {
    id: 'v17',
    word: 'Profound',
    partOfSpeech: 'adjective',
    phonetic: '/prəˈfaʊnd/',
    difficulty: 'intermediate',
    correctDefinition: 'Very great or intense; having or showing great knowledge or insight.',
    exampleSentence: 'The book had a profound influence on his philosophical beliefs.',
    synonyms: ['Deep', 'Intense', 'Insightful', 'Wise'],
    antonyms: ['Superficial', 'Shallow', 'Trivial']
  },
  {
    id: 'v18',
    word: 'Mitigate',
    partOfSpeech: 'verb',
    phonetic: '/ˈmɪt.ɪ.ɡeɪt/',
    difficulty: 'intermediate',
    correctDefinition: 'Make less severe, serious, or painful.',
    exampleSentence: 'Engineers planted trees along the slope to mitigate the risk of landslides.',
    synonyms: ['Alleviate', 'Lessen', 'Diminish', 'Moderate'],
    antonyms: ['Aggravate', 'Exacerbate', 'Worsen']
  },
  {
    id: 'v19',
    word: 'Resolute',
    partOfSpeech: 'adjective',
    phonetic: '/ˈrɛz.ə.luːt/',
    difficulty: 'intermediate',
    correctDefinition: 'Admirably purposeful, determined, and unwavering in decision.',
    exampleSentence: 'She remained resolute in her decision to launch the nonprofit organization.',
    synonyms: ['Determined', 'Unwavering', 'Steadfast', 'Adamant'],
    antonyms: ['Hesitant', 'Vacillating', 'Uncertain']
  },
  {
    id: 'v20',
    word: 'Candid',
    partOfSpeech: 'adjective',
    phonetic: '/ˈkæn.dɪd/',
    difficulty: 'beginner',
    correctDefinition: 'Truthful and straightforward; frank without disguise.',
    exampleSentence: 'His candid interview gave fans a realistic look at life as an artist.',
    synonyms: ['Frank', 'Blunt', 'Honest', 'Outspoken'],
    antonyms: ['Guarded', 'Insincere', 'Deceptive']
  },
  {
    id: 'v21',
    word: 'Diligent',
    partOfSpeech: 'adjective',
    phonetic: '/ˈdɪl.ɪ.dʒənt/',
    difficulty: 'beginner',
    correctDefinition: 'Having or showing care and conscientiousness in one’s work or duties.',
    exampleSentence: 'Thanks to diligent study, she scored in the top percentile of her class.',
    synonyms: ['Conscientious', 'Hardworking', 'Assiduous', 'Attentive'],
    antonyms: ['Lazy', 'Negligent', 'Careless']
  },
  {
    id: 'v22',
    word: 'Audacious',
    partOfSpeech: 'adjective',
    phonetic: '/ɔːˈdeɪ.ʃəs/',
    difficulty: 'advanced',
    correctDefinition: 'Showing a willingness to take surprisingly bold risks, or showing an impudent lack of respect.',
    exampleSentence: 'The daring explorer devised an audacious plan to cross the desert alone.',
    synonyms: ['Bold', 'Daring', 'Fearless', 'Brazen'],
    antonyms: ['Timid', 'Cautious', 'Meek']
  },
  {
    id: 'v23',
    word: 'Superfluous',
    partOfSpeech: 'adjective',
    phonetic: '/suːˈpɜː.flu.əs/',
    difficulty: 'advanced',
    correctDefinition: 'Unnecessary, especially through being more than enough; redundant.',
    exampleSentence: 'Edit your essay thoroughly to remove any superfluous adverbs and repetition.',
    synonyms: ['Redundant', 'Excessive', 'Surplus', 'Unneeded'],
    antonyms: ['Essential', 'Necessary', 'Vital']
  },
  {
    id: 'v24',
    word: 'Concur',
    partOfSpeech: 'verb',
    phonetic: '/kənˈkɜːr/',
    difficulty: 'intermediate',
    correctDefinition: 'Be of the same opinion; agree with another view or finding.',
    exampleSentence: 'The panel of medical specialists concurred with the initial diagnosis.',
    synonyms: ['Agree', 'Accord', 'Harmonize', 'Coincide'],
    antonyms: ['Disagree', 'Dissent', 'Object']
  },
  {
    id: 'v25',
    word: 'Enigmatic',
    partOfSpeech: 'adjective',
    phonetic: '/ˌɛn.ɪɡˈmæt.ɪk/',
    difficulty: 'advanced',
    correctDefinition: 'Difficult to interpret or understand; mysterious or puzzling.',
    exampleSentence: 'The Mona Lisa is famous worldwide for her enigmatic smile.',
    synonyms: ['Mysterious', 'Inscrutable', 'Cryptic', 'Perplexing'],
    antonyms: ['Clear', 'Straightforward', 'Obvious']
  },
  {
    id: 'v26',
    word: 'Articulate',
    partOfSpeech: 'verb',
    phonetic: '/ɑːˈtɪk.jʊ.leɪt/',
    difficulty: 'beginner',
    correctDefinition: 'Express an idea or feeling fluently and coherently.',
    exampleSentence: 'She was able to articulate her project vision with remarkable poise.',
    synonyms: ['Express', 'Voice', 'Pronounce', 'Enunciate'],
    antonyms: ['Mumble', 'Misrepresent', 'Stumble']
  },
  {
    id: 'v27',
    word: 'Pivotal',
    partOfSpeech: 'adjective',
    phonetic: '/ˈpɪv.ə.təl/',
    difficulty: 'intermediate',
    correctDefinition: 'Of crucial importance in relation to the development or success of something else.',
    exampleSentence: 'The discovery of penicillin was a pivotal moment in medical history.',
    synonyms: ['Crucial', 'Decisive', 'Critical', 'Central'],
    antonyms: ['Minor', 'Incidental', 'Trivial']
  },
  {
    id: 'v28',
    word: 'Nostalgia',
    partOfSpeech: 'noun',
    phonetic: '/nɒˈstæl.dʒə/',
    difficulty: 'beginner',
    correctDefinition: 'A sentimental longing or wistful affection for a period in the past.',
    exampleSentence: 'Listening to songs from high school filled him with warm nostalgia.',
    synonyms: ['Reminiscence', 'Wistfulness', 'Yearning', 'Longing'],
    antonyms: ['Future-focus', 'Forgetfulness']
  },
  {
    id: 'v29',
    word: 'Anachronism',
    partOfSpeech: 'noun',
    phonetic: '/əˈnæk.rə.nɪ.zəm/',
    difficulty: 'advanced',
    correctDefinition: 'A thing belonging or appropriate to a period other than that in which it exists, especially something old-fashioned.',
    exampleSentence: 'Seeing a wristwatch in a movie set in ancient Rome was a glaring anachronism.',
    synonyms: ['Misplacement', 'Archaism', 'Incongruity', 'Chronological error'],
    antonyms: ['Synchronism', 'Contemporary']
  },
  {
    id: 'v30',
    word: 'Juxtaposition',
    partOfSpeech: 'noun',
    phonetic: '/ˌdʒʌk.stə.pəˈzɪʃ.ən/',
    difficulty: 'advanced',
    correctDefinition: 'The fact of two things being placed close together with contrasting effect.',
    exampleSentence: 'The film uses the juxtaposition of serene countryside and chaotic city streets to great effect.',
    synonyms: ['Contrast', 'Comparison', 'Collocation', 'Proximity'],
    antonyms: ['Separation', 'Isolation']
  },
  {
    id: 'v31',
    word: 'Aesthetic',
    partOfSpeech: 'adjective',
    phonetic: '/ɛsˈθɛt.ɪk/',
    difficulty: 'intermediate',
    correctDefinition: 'Concerned with beauty or the appreciation of beauty.',
    exampleSentence: 'The minimalist interior design gave the room a clean aesthetic appeal.',
    synonyms: ['Artistic', 'Tasteful', 'Graceful', 'Pleasing'],
    antonyms: ['Unsightly', 'Ugly', 'Unappealing']
  },
  {
    id: 'v32',
    word: 'Sycophant',
    partOfSpeech: 'noun',
    phonetic: '/ˈsɪk.ə.fænt/',
    difficulty: 'advanced',
    correctDefinition: 'A person who acts obsequiously toward someone important in order to gain advantage.',
    exampleSentence: 'The emperor was surrounded by sycophants who praised even his worst decrees.',
    synonyms: ['Flatterer', 'Yes-man', 'Bootlicker', 'Toady'],
    antonyms: ['Critic', 'Rebel', 'Freethinker']
  },
  {
    id: 'v33',
    word: 'Cacophony',
    partOfSpeech: 'noun',
    phonetic: '/kəˈkɒf.ə.ni/',
    difficulty: 'advanced',
    correctDefinition: 'A harsh, discordant mixture of sounds.',
    exampleSentence: 'A cacophony of blaring horns and drilling echoed through the morning traffic.',
    synonyms: ['Din', 'Racket', 'Discordance', 'Clatter'],
    antonyms: ['Harmony', 'Melody', 'Symphony']
  },
  {
    id: 'v34',
    word: 'Euphoria',
    partOfSpeech: 'noun',
    phonetic: '/juːˈfɔː.ri.ə/',
    difficulty: 'intermediate',
    correctDefinition: 'A feeling or state of intense excitement and happiness.',
    exampleSentence: 'Winning the national championship sent the stadium into an uncontrollable euphoria.',
    synonyms: ['Elation', 'Ecstasy', 'Jubilation', 'Bliss'],
    antonyms: ['Misery', 'Depression', 'Melancholy']
  },
  {
    id: 'v35',
    word: 'Altruism',
    partOfSpeech: 'noun',
    phonetic: '/ˈæl.tru.ɪ.zəm/',
    difficulty: 'intermediate',
    correctDefinition: 'Disinterested and selfless concern for the well-being of others.',
    exampleSentence: 'Her lifetime of volunteering was an exemplary demonstration of altruism.',
    synonyms: ['Selflessness', 'Benevolence', 'Charity', 'Philanthropy'],
    antonyms: ['Selfishness', 'Egoism']
  },
  {
    id: 'v36',
    word: 'Gregarious',
    partOfSpeech: 'adjective',
    phonetic: '/ɡrɪˈɡeə.ri.əs/',
    difficulty: 'advanced',
    correctDefinition: 'Fond of company; sociable and enjoying the company of others.',
    exampleSentence: 'As a gregarious person, he was naturally the center of conversation at dinner parties.',
    synonyms: ['Sociable', 'Companionable', 'Outgoing', 'Convivial'],
    antonyms: ['Reclusive', 'Introverted', 'Antisocial']
  },
  {
    id: 'v37',
    word: 'Lethargic',
    partOfSpeech: 'adjective',
    phonetic: '/ləˈθɑː.dʒɪk/',
    difficulty: 'beginner',
    correctDefinition: 'Affected by lethargy; sluggish and apathetic.',
    exampleSentence: 'Recovering from the flu left him feeling drained and lethargic for days.',
    synonyms: ['Sluggish', 'Inert', 'Tired', 'Torpid'],
    antonyms: ['Energetic', 'Vigorous', 'Lively']
  },
  {
    id: 'v38',
    word: 'Malleable',
    partOfSpeech: 'adjective',
    phonetic: '/ˈmæl.i.ə.bəl/',
    difficulty: 'intermediate',
    correctDefinition: 'Easily influenced, pliable, or able to be hammered or pressed permanently out of shape.',
    exampleSentence: 'Gold is extremely malleable and can be beaten into thin sheets.',
    synonyms: ['Pliant', 'Ductile', 'Adaptable', 'Yielding'],
    antonyms: ['Rigid', 'Inflexible', 'Intractable']
  },
  {
    id: 'v39',
    word: 'Ostentatious',
    partOfSpeech: 'adjective',
    phonetic: '/ˌɒs.tɛnˈteɪ.ʃəs/',
    difficulty: 'advanced',
    correctDefinition: 'Characterized by vulgar or pretentious display; designed to impress or attract notice.',
    exampleSentence: 'The mansion featured an ostentatious fountain decorated in solid gold.',
    synonyms: ['Showy', 'Pretentious', 'Flamboyant', 'Gaudy'],
    antonyms: ['Modest', 'Understated', 'Subtle']
  },
  {
    id: 'v40',
    word: 'Paradigm',
    partOfSpeech: 'noun',
    phonetic: '/ˈpær.ə.daɪm/',
    difficulty: 'advanced',
    correctDefinition: 'A typical example or pattern of something; a model or overarching framework.',
    exampleSentence: 'The advent of the internet caused a fundamental paradigm shift in modern media.',
    synonyms: ['Model', 'Standard', 'Prototype', 'Archetype'],
    antonyms: ['Anomaly', 'Deviation']
  },
  {
    id: 'v41',
    word: 'Quixotic',
    partOfSpeech: 'adjective',
    phonetic: '/kwɪkˈsɒt.ɪk/',
    difficulty: 'advanced',
    correctDefinition: 'Exceedingly idealistic; unrealistic and impractical.',
    exampleSentence: 'His quixotic quest to eliminate all world traffic with flying cars baffled city planners.',
    synonyms: ['Idealistic', 'Visionary', 'Utopian', 'Chimerical'],
    antonyms: ['Pragmatic', 'Realistic', 'Sensible']
  },
  {
    id: 'v42',
    word: 'Rhetoric',
    partOfSpeech: 'noun',
    phonetic: '/ˈrɛt.ər.ɪk/',
    difficulty: 'intermediate',
    correctDefinition: 'The art of effective or persuasive speaking or writing.',
    exampleSentence: 'The politician was praised for inspiring rhetoric that rallied voters.',
    synonyms: ['Oratory', 'Eloquence', 'Persuasion', 'Discourse'],
    antonyms: ['Inarticulacy', 'Quietude']
  },
  {
    id: 'v43',
    word: 'Scrutiny',
    partOfSpeech: 'noun',
    phonetic: '/ˈskruː.tɪ.ni/',
    difficulty: 'intermediate',
    correctDefinition: 'Critical observation or examination; close inspection.',
    exampleSentence: 'The company finances came under intense scrutiny during the federal audit.',
    synonyms: ['Inspection', 'Examination', 'Analysis', 'Investigation'],
    antonyms: ['Inattention', 'Neglect', 'Glance']
  },
  {
    id: 'v44',
    word: 'Taciturn',
    partOfSpeech: 'adjective',
    phonetic: '/ˈtæs.ɪ.tɜːn/',
    difficulty: 'advanced',
    correctDefinition: 'Reserved or uncommunicative in speech; saying little.',
    exampleSentence: 'Her grandfather was a taciturn man who spoke only when it was necessary.',
    synonyms: ['Untalkative', 'Reticent', 'Quiet', 'Reserved'],
    antonyms: ['Loquacious', 'Talkative', 'Garrulous']
  },
  {
    id: 'v45',
    word: 'Venerable',
    partOfSpeech: 'adjective',
    phonetic: '/ˈvɛn.ər.ə.bəl/',
    difficulty: 'advanced',
    correctDefinition: 'Accorded a great deal of respect, especially because of age, wisdom, or character.',
    exampleSentence: 'The venerable university has educated Nobel laureates for over four centuries.',
    synonyms: ['Respected', 'Revered', 'Honored', 'Distinguished'],
    antonyms: ['Disreputable', 'Unworthy']
  },
  {
    id: 'v46',
    word: 'Zealous',
    partOfSpeech: 'adjective',
    phonetic: '/ˈzɛl.əs/',
    difficulty: 'intermediate',
    correctDefinition: 'Having or showing great energy or enthusiasm in pursuit of a cause or objective.',
    exampleSentence: 'The zealous environmental activists organized cleanups in twenty cities.',
    synonyms: ['Passionate', 'Fervent', 'Ardent', 'Enthusiastic'],
    antonyms: ['Apathetic', 'Indifferent', 'Passive']
  },
  {
    id: 'v47',
    word: 'Amicable',
    partOfSpeech: 'adjective',
    phonetic: '/ˈæm.ɪ.kə.bəl/',
    difficulty: 'beginner',
    correctDefinition: 'Characterized by friendly goodwill and peaceable relations.',
    exampleSentence: 'After weeks of negotiation, both business partners reached an amicable agreement.',
    synonyms: ['Friendly', 'Cordially', 'Harmonious', 'Peaceable'],
    antonyms: ['Hostile', 'Adversarial', 'Unfriendly']
  },
  {
    id: 'v48',
    word: 'Brevity',
    partOfSpeech: 'noun',
    phonetic: '/ˈbrɛv.ɪ.ti/',
    difficulty: 'intermediate',
    correctDefinition: 'Concise and exact use of words in writing or speech; shortness of time.',
    exampleSentence: 'The CEO appreciated brevity in emails, preferring bullet points over lengthy essays.',
    synonyms: ['Conciseness', 'Shortness', 'Pithiness', 'Succinctness'],
    antonyms: ['Verbosity', 'Wordiness', 'Prolixity']
  },
  {
    id: 'v49',
    word: 'Circumspect',
    partOfSpeech: 'adjective',
    phonetic: '/ˈsɜː.kəm.spɛkt/',
    difficulty: 'advanced',
    correctDefinition: 'Wary and unwilling to take risks; prudent and cautious.',
    exampleSentence: 'Investors were circumspect about committing capital to the untested venture.',
    synonyms: ['Cautious', 'Wary', 'Prudent', 'Guarded'],
    antonyms: ['Reckless', 'Rash', 'Impulsive']
  },
  {
    id: 'v50',
    word: 'Deference',
    partOfSpeech: 'noun',
    phonetic: '/ˈdɛf.ər.əns/',
    difficulty: 'intermediate',
    correctDefinition: 'Humble submission and respect shown to an elder, authority, or superior.',
    exampleSentence: 'Out of deference to the visiting ambassador, all proceedings paused.',
    synonyms: ['Respect', 'Reverence', 'Regard', 'Esteem'],
    antonyms: ['Disrespect', 'Defiance', 'Contempt']
  },
  {
    id: 'v51',
    word: 'Equanimity',
    partOfSpeech: 'noun',
    phonetic: '/ˌɛk.wəˈnɪm.ɪ.ti/',
    difficulty: 'advanced',
    correctDefinition: 'Mental calmness, composure, and evenness of temper, especially in a difficult situation.',
    exampleSentence: 'She handled the sudden server outage with remarkable poise and equanimity.',
    synonyms: ['Composure', 'Serenity', 'Calmness', 'Equilibrium'],
    antonyms: ['Agitation', 'Anxiety', 'Panic']
  },
  {
    id: 'v52',
    word: 'Fortitude',
    partOfSpeech: 'noun',
    phonetic: '/ˈfɔː.tɪ.tjuːd/',
    difficulty: 'intermediate',
    correctDefinition: 'Courage in pain or adversity; mental and emotional strength.',
    exampleSentence: 'The trapped miners showed extraordinary fortitude while awaiting rescue.',
    synonyms: ['Courage', 'Bravery', 'Endurance', 'Grit'],
    antonyms: ['Cowardice', 'Weakness', 'Timidness']
  },
  {
    id: 'v53',
    word: 'Gratuitous',
    partOfSpeech: 'adjective',
    phonetic: '/ɡrəˈtjuː.ɪ.təs/',
    difficulty: 'advanced',
    correctDefinition: 'Uncalled for; lacking good reason; unwarranted, or given free of charge.',
    exampleSentence: 'The movie was criticized for including scenes of gratuitous violence.',
    synonyms: ['Unjustified', 'Unprovoked', 'Unwarranted', 'Needless'],
    antonyms: ['Justified', 'Necessary', 'Warranted']
  },
  {
    id: 'v54',
    word: 'Haughty',
    partOfSpeech: 'adjective',
    phonetic: '/ˈhɔː.ti/',
    difficulty: 'intermediate',
    correctDefinition: 'Arrogantly superior and disdainful of others.',
    exampleSentence: 'The haughty aristocrat looked down upon the commoners in the market.',
    synonyms: ['Arrogant', 'Conceited', 'Pompous', 'Condescending'],
    antonyms: ['Humble', 'Modest', 'Unassuming']
  },
  {
    id: 'v55',
    word: 'Impetuous',
    partOfSpeech: 'adjective',
    phonetic: '/ɪmˈpɛtʃ.u.əs/',
    difficulty: 'intermediate',
    correctDefinition: 'Acting or done quickly and without thought or care.',
    exampleSentence: 'His impetuous decision to quit his job shocked his family.',
    synonyms: ['Impulsive', 'Rash', 'Hasty', 'Reckless'],
    antonyms: ['Considered', 'Cautious', 'Deliberate']
  },
  {
    id: 'v56',
    word: 'Judicious',
    partOfSpeech: 'adjective',
    phonetic: '/dʒuːˈdɪʃ.əs/',
    difficulty: 'intermediate',
    correctDefinition: 'Having, showing, or done with good judgment or sense.',
    exampleSentence: 'Through judicious investments, the university grew its endowment considerably.',
    synonyms: ['Sensible', 'Prudent', 'Wise', 'Discreet'],
    antonyms: ['Injudicious', 'Foolish', 'Unwise']
  },
  {
    id: 'v57',
    word: 'Kinetic',
    partOfSpeech: 'adjective',
    phonetic: '/kɪˈnɛt.ɪk/',
    difficulty: 'beginner',
    correctDefinition: 'Relating to or resulting from motion; dynamic and active.',
    exampleSentence: 'The modern sculpture possessed a kinetic beauty as the wind spun its blades.',
    synonyms: ['Dynamic', 'Energized', 'Active', 'Moving'],
    antonyms: ['Static', 'Stationary', 'Inert']
  },
  {
    id: 'v58',
    word: 'Lament',
    partOfSpeech: 'verb',
    phonetic: '/ləˈmɛnt/',
    difficulty: 'beginner',
    correctDefinition: 'Express regret, sorrow, or disappointment about something.',
    exampleSentence: 'Historians lament the loss of priceless ancient manuscripts to fire.',
    synonyms: ['Mourn', 'Grieve', 'Deplore', 'Regret'],
    antonyms: ['Celebrate', 'Rejoice']
  },
  {
    id: 'v59',
    word: 'Magnanimous',
    partOfSpeech: 'adjective',
    phonetic: '/mæɡˈnæn.ɪ.məs/',
    difficulty: 'advanced',
    correctDefinition: 'Generous or forgiving, especially toward a rival or less powerful person.',
    exampleSentence: 'In victory, the coach was magnanimous, praising the valiant efforts of his opponents.',
    synonyms: ['Generous', 'Noble', 'Charitable', 'Forgiving'],
    antonyms: ['Petty', 'Spiteful', 'Vindictive']
  },
  {
    id: 'v60',
    word: 'Nebulous',
    partOfSpeech: 'adjective',
    phonetic: '/ˈnɛb.jʊ.ləs/',
    difficulty: 'advanced',
    correctDefinition: 'In the form of a cloud or haze; hazy, unclear, vague, or ill-defined.',
    exampleSentence: 'The startup offered a nebulous business plan that left venture capitalists skeptical.',
    synonyms: ['Vague', 'Hazy', 'Indistinct', 'Ambiguous'],
    antonyms: ['Clear', 'Distinct', 'Concrete']
  },
  {
    id: 'v61',
    word: 'Obdurate',
    partOfSpeech: 'adjective',
    phonetic: '/ˈɒb.djʊ.rət/',
    difficulty: 'advanced',
    correctDefinition: 'Stubbornly refusing to change one’s opinion or course of action.',
    exampleSentence: 'Despite overwhelming evidence, the politician remained obdurate in his denial.',
    synonyms: ['Stubborn', 'Obstinate', 'Intransigent', 'Inflexible'],
    antonyms: ['Malleable', 'Compliant', 'Tractable']
  },
  {
    id: 'v62',
    word: 'Parsimonious',
    partOfSpeech: 'adjective',
    phonetic: '/ˌpɑː.sɪˈməʊ.ni.əs/',
    difficulty: 'advanced',
    correctDefinition: 'Unwilling to spend money or use resources; stingy or frugal to an extreme.',
    exampleSentence: 'The parsimonious landlord refused to replace the broken heating system.',
    synonyms: ['Miserly', 'Stingy', 'Tightfisted', 'Frugal'],
    antonyms: ['Generous', 'Extravagant', 'Lavish']
  }
];
